FROM alpine:3.18.3
LABEL maintainer="Steven R. Loomis <srl295@gmail.com>" org.opencontainers.image.source="https://github.com/codehivetx/halos"
# install base stuff
# will initialize stuff, but we can ignore it
# keep all data here
VOLUME /data
ADD /sbin/ /usr/local/sbin/

